app/flux/studentStore.js, test/flux/studentStore.test.js
Should cover: 
via "it loads student from storage", "it handles loading zero students from storage", "it loads the given id from storage", and "it removes broken students from storage".
=> Finish adding studentStore tests

app/elements/studentList.js, app/flux/studentActions.js, app/flux/studentStore.js
Added an import student button on the student list home page. The is necessary as we need to pull in son files without going into local storage.
=> Import student

app/elements/searchButton.js, app/elements/student.js, app/helpers/courses.js, app/helpers/queryTreoDatabase.js, app/styles/app/_loading.scss, app/styles/app/_searchButton.scss
This PR adds a few things:
1. It adds a "No Results Found" message when the query doesn't return anything.
2. It adds a loading spinner while the query is executing.
3. It prevents multiple queries from being executed at once.
4. It requires that you include at least one letter in the query.
5. It breaks the giant `searchButton.query` function into two functions.
=> Add search progress indicators

app/elements/course.js, app/elements/semester.js, package.json
=> Update react-dnd to v0.9

area-data/majors/asian-studies.yaml, src/components/expression.js, src/lib/compute-chunk.js, src/lib/compute-count-with-operator.js, src/lib/humanize-operator.js, src/lib/parse-hanson-string.js, src/lib/parse-hanson-string.pegjs, test/areas/collect-matches.test.js, test/areas/collect-used-courses.test.js, test/areas/compute-boolean.test.js, test/areas/compute-count-with-operator.test.js, test/areas/compute-modifier.test.js, test/areas/compute-occurrence.test.js, test/areas/compute-of.test.js, test/areas/get-matches-from-children.test.js, test/areas/parse-hanson-string.test.js
In Asian Studies, we needed the ability to say "you may only take at most two Level 1 courses."
So, I added that ability.
=> Support 'at most <n>' and 'exactly <n>' qualifiers for counters

package.json, src/lib/compute-chunk.js, test/areas/compute-boolean.test.js, test/areas/compute-chunk.test.js, test/areas/compute-modifier.test.js, test/areas/compute-reference.test.js
I went through the line-by-line coverage for computeChunk.js, and added tests for (hopefully) all of the uncovered lines.
=> More tests!

area-data/concentrations/africa-and-the-americas.yaml, area-data/concentrations/africa-and-the-americas.yaml.ip
Added full codification of the Africa and the Americas concentration.
=> Added completed africa-and-the-americas concentration, removed in progress file

area-data/concentrations/africa-and-the-americas.yaml, area-data/concentrations/race-and-ethnic-studies.yaml.ip, area-data/concentrations/womens-and-gender-studies.yaml, area-data/majors/race-and-ethnic-studies.yaml.ip, area-data/majors/russian-area-studies.yaml.ip, area-data/majors/russian.yaml.ip, area-data/majors/womens-and-gender-studies.yaml.ip, src/components/area-of-study.js, src/components/area-of-study.scss, src/lib/enhance-hanson.js, src/lib/find-area-path.js
=> Allow people to view the catalog page with a link

src/lib/expand-department.js
It's for the EN/LI 250 course.
=> Add "EN" as a valid department shorthand

bin/evaluate.js, package.json
=> port bin/evaluate to nomnom and remove meow dep

package.json
:rocket:
react-router just published version 0.13.4, so that’s now up to date in your `package.json`.
Check that it doesn’t break your code and release the new version of your software safe in the knowledge that it will stay in this working state.
---
This pull request was created by [greenkeeper.io](http://greenkeeper.io/).
It keeps your software, up to date, all the time.
<sub>
Tired of seeing this sponsor message? Upgrade to the supporter plan!
You'll also get your pull requests faster :zap:
</sub>
=> Updated react-router to version 0.13.4

package.json, src/lib/check-student-against-area.js, src/models/schedule.js, src/models/student.js
saves 200K by not including a buffer implementation
=> switch from node-uuid to uuid

area-data/majors/biology-2014-15.yaml
Pending a decision on the name of 'valid through'
=> Initial draft of old biology major

area-data/concentrations/neuroscience-2011-12.yaml, area-data/concentrations/neuroscience-2014-15.yaml
Yo, @drewvolz: what were we stuck on with this? Any idea/
=> Nueroscience update

.travis.yml, bin/olaf-find-student-courses.js, src/area-tools/filter-by-where-clause.js, src/components/expression--course.js, src/helpers/check-student-against-area.worker.js, test/areas/filter-by-qualification.test.js, test/areas/filter-by-where-clause.test.js
=> Fix "distinct"

package.json
=> chore(package): update react-addons-perf to version 0.14.5

package.json
=> chore(package): update react-dom to version 0.14.5

src/area-tools/compute-chunk.js
We can't use computeCountWithOperator, because 0 <= N ∀ N.
Instead, we check to see if the next step would cause us to go over our limit. If it would, we stop the loop.
(See the new comments in the code for more explanation.)
@drewvolz: take a peek when you've got a 'mo, plz!
=> Fix at-most queries (and keep at-least greedy)

package.json, src/helpers/convert-imported-student.js, src/helpers/get-courses.js, src/helpers/import-student.js, src/routes/app_content_new-student/routes/sis/sis-import.js, test/helpers/import-student.test.js
- import them whenever they don't show up in the database, rather than based on the term
=> Import student, take two

src/area-tools/compute-chunk.js, src/area-tools/filter-by-where-clause.js, src/area-tools/parse-hanson-string.pegjs, test/areas/filter-by-qualification.test.js, test/areas/filter-by-where-clause.test.js
it's also in:
- modifiers
- where-expressions
- occurrence expressions
This PR adds support for the other places.
=> at-most doesn't just apply to of-expressions

src/area-tools/apply-fulfillment-to-expression.js, src/area-tools/apply-fulfillment-to-result.js, src/area-tools/compute-chunk.js, src/area-tools/compute.js, src/area-tools/evaluate.js, src/area-tools/get-fulfillment.js, src/helpers/alter-course-for-evaluation.js, src/helpers/check-student-against-area.worker.js, src/helpers/embed-active-student-courses.js, src/helpers/fulfill-fulfillments.js, src/helpers/get-student-data.js, src/helpers/save-student.js, src/models/student.js, src/routes/app_content_student/components/expression.js, src/routes/app_content_student/components/expression.scss
Fulfillments are like overrides, but instead of saying "this passed", they essentially let you edit the contents of a requirement at runtime.
I intend to expose them through the course detail view.
They will allow you to apply courses taken elsewhere to your St. Olaf majors, if you want.
=> Fulfillments

area-data/majors/dance.yaml, area-data/majors/dance.yaml.ip
=> add the dance major

README.md
=> Update README.md to remove qualifier for Edge support

scripts/deploy.sh, src/index.js
This means we're almost done relying on St. Olaf infrastructure.
The last two pieces are sis importing, and course data. Course data has already moved, but I changed some of the data formats so we'll need to audit Gobbldygook for those changes.
=> Deploy to github pages

package.json, scripts/deploy.sh
It wasn't rendering on gh-pages. Turns out that we needed to pin `history` to v2.
=> Fix gh-pages deploy

.babelrc, .eslintignore, .webpackrc.js, modules/web/helpers/load-data.worker.js, package.json, yarn.lock
It now compiles about 30 seconds faster.
Everything still works.
=> Upgrade to Webpack@2

package.json
=> fix(package): update debug to version 2.5.1

package.json
=> chore(package): update js-beautify to version 1.6.6

package.json
=> chore(package): update babel-plugin-istanbul to version 3.1.2

package.json
=> fix(package): update redux-thunk to version 2.1.2

.travis.yml
=> go back to one travis job

.travis.yml
=> split up travis into three jobs again

.webpackrc.js, modules/web/routes/student/components/requirement.scss, yarn.lock
Reverts 4e0e23d05d7915993622c214b9b408b9c0158272, part of #1189.
=> Fix webpack-reorg

.travis.yml, circle.yml, scripts/update-yarn-lock-file.sh
from https://github.com/devtools-html/debugger.html/blob/master/bin/update-yarn-lock-file
=> add script to update yarn lockfile from travis

package.json
=> fix(package): update js-yaml to version 3.8.1

package.json
=> chore(package): update prettier to version 0.17.1

package.json
=> fix(package): update codemirror to version 5.24.2

modules/examine-student/__tests__/__snapshots__/apply-filter.test.js.snap, modules/examine-student/__tests__/__snapshots__/collect-matches.test.js.snap, modules/examine-student/__tests__/__snapshots__/collect-taken-courses.test.js.snap, modules/examine-student/__tests__/__snapshots__/compute-boolean.test.js.snap, modules/examine-student/__tests__/__snapshots__/compute-course.test.js.snap, modules/examine-student/__tests__/__snapshots__/compute-modifier.test.js.snap, modules/hanson-format/__tests__/__snapshots__/enhance-hanson.test.js.snap, modules/hanson-format/__tests__/parse-hanson-string/__snapshots__/boolean-expression.test.js.snap, modules/hanson-format/__tests__/parse-hanson-string/__snapshots__/counters.test.js.snap, modules/hanson-format/__tests__/parse-hanson-string/__snapshots__/course-expression.test.js.snap, modules/hanson-format/__tests__/parse-hanson-string/__snapshots__/filter-expression.test.js.snap, modules/hanson-format/__tests__/parse-hanson-string/__snapshots__/modifier-expression.test.js.snap, modules/hanson-format/__tests__/parse-hanson-string/__snapshots__/occurrence-expression.test.js.snap, modules/hanson-format/__tests__/parse-hanson-string/__snapshots__/of-expression.test.js.snap, modules/hanson-format/__tests__/parse-hanson-string/__snapshots__/reference-expression.test.js.snap, modules/hanson-format/__tests__/parse-hanson-string/__snapshots__/where-expression.test.js.snap, modules/object-student/__tests__/__snapshots__/find-course-warnings.test.js.snap, modules/object-student/__tests__/__snapshots__/prepare-student-for-save.test.js.snap, modules/object-student/__tests__/__snapshots__/schedule.test.js.snap, modules/object-student/__tests__/__snapshots__/sort-studies-by-type.test.js.snap, modules/search-queries/__tests__/__snapshots__/build-query-from-string.test.js.snap, modules/search-queries/__tests__/__snapshots__/query-courses.test.js.snap, package.json
=> chore(package): update jest to version 19.0.2

package.json
=> chore(package): update node-sass to version 4.5.0

package.json
=> chore(package): update prettier to version 0.21.0

.eslintrc.yml, package.json
=> chore(package): update eslint to version 3.17.0

package.json
=> fix(package): update react-modal to version 1.7.1

package.json
=> fix(package): update react-dropzone to version 3.12.0

circle.yml, modules/web/__tests__/.eslintrc.yml, modules/web/__tests__/app-container.test.js, package.json, yarn.lock
This now tests that the app renders successfully, and that the rendered app can navigate to `/create`.
=> Add initial all-app tests

.webpackrc.js, package.json
I missed the webpack config last time.
=> Prettier2: More Pretty!

modules/web/components/content-editable.js, modules/web/modules/student/__tests__/.eslintrc.yml, modules/web/modules/student/__tests__/__snapshots__/student-summary.test.js.snap, modules/web/modules/student/__tests__/student-summary.test.js, modules/web/modules/student/student-summary.js
- Change `<ContentEditable/>` to take a `[disabled]` prop instead of an `[editable]` prop
- Make onChange\* properties as optional in StudentSummary's children
- Remove the last element of randomness from the non-random welcome message
- Add tests for all child components of StudentSummary
- Fix the problem where a student with no degrees and no majors rendered as "You have no degrees0."
=> Fix StudentSummary rendering 0 with no degrees

modules/web/modules/student/__tests__/__snapshots__/student-summary.test.js.snap, modules/web/modules/student/__tests__/student-summary.test.js, modules/web/modules/student/student-summary.js
I think this'll get that file to 100% coverage
=> More StudentSummary tests

package.json
=> chore(package): update redux-logger to version 2.9.1

package.json
=> chore(package): update duplicate-package-checker-webpack-plugin to v1.2.4

package.json
=> chore(package): update webpack to version 2.3.1

package.json
=> chore(package): update prop-types to version 15.5.7

package.json
=> fix(package): update react-modal to version 1.7.6

package.json
=> chore(package): update prettier to version 1.2.1

package.json
=> fix(package): update debug to version 2.6.6

package.json
=> fix(package): update react-input-autosize to version 1.1.3

package.json
=> chore(package): update redux-logger to version 3.0.3

package.json
=> chore(package): update redux-logger to version 3.0.6

package.json
=> chore(package): update prettier to version 1.4.1

package.json
=> fix(package): update react-modal to version 1.7.11

package.json
=> fix(package): update react-modal to version 1.9.6

package.json
=> chore(package): update eslint-plugin-import to version 2.5.0

package.json
=> chore(package): update jest-enzyme to version 3.5.1

package.json
=> chore(package): update jest-enzyme to version 3.5.3

package.json
=> chore(package): update json-loader to version 0.5.6

modules/examine-student/compute.js, package.json
=> remove es6-set

package.json
=> fix(package): update react-input-autosize to version 2.0.0

package.json
=> chore(package): update eslint-config-prettier to version 2.5.0

package.json
=> fix(package): update react-dnd to version 2.5.3

package.json
=> fix(package): update react-modal to version 3.0.3

package.json
=> chore(package): update flow-remove-types to version 1.2.3

modules/web/routes/create/method-manual.js
Closes https://github.com/hawkrives/gobbldygook/issues/1816
---
The problem here was that I was calling setState, an asynchronous operation, and then calling a function that depended upon the new state (which hadn't been set yet).
I've edited it to use the setState callback function, which is called once the state has actually changed.
=> fix matriculation/graduation bug

package.json
=> chore(package): update chalk to version 2.3.0

package.json
=> chore(package): update copy-webpack-plugin to version 4.2.3

package.json
=> fix(package): update react-input-autosize to version 2.1.2

package.json
=> fix(package): update react-select to version 1.0.1

package.json
=> fix(package): update react-modal to version 3.1.10

package.json
=> fix(package): update es6-promise to version 4.2.2

package.json
=> fix(package): update react-dropzone to version 4.2.7

package.json
=> chore(package): update webpack-dev-server to version 2.11.0

modules/gob-web/index.js, modules/gob-web/package.json, modules/gob-worker-load-data/index.worker.js, modules/gob-worker-load-data/package.json
I'm mainly curious what buildsize will say here
=> Remove whatwg-fetch polyfill

modules/gob-examine-student/source/__tests__/count-terms.test.js, modules/gob-examine-student/source/compute-chunk.js, modules/gob-examine-student/source/count-terms.js, modules/gob-hanson-format/package.json, modules/gob-hanson-format/parse-hanson-string.js, modules/gob-hanson-format/parse-hanson-string.pegjs
Adds support for `three terms from courses where …` Hanson expressions.
This came out of adapting Gobbldygook for Carleton.
=> Add support for counting "terms" in examineStudent

modules/gob-web/modules/course-searcher/redux/reducers.js
Closes https://github.com/hawkrives/gobbldygook/issues/2206
It now has explicit ordering for each SORT_BY key, instead of only applying the chosen sort after `[year, semester, deptnum]`.
=> Fix up ordering and grouping of search results

modules/gob-web/redux/middleware/check-students.js, package.json
Closes https://github.com/hawkrives/gobbldygook/issues/2225
=> Fix undefined check arg

.circleci/config.yml, .travis.yml, netlify.toml, package.json
update Travis and Circle to use Node 10.
=> Use Node 10 on CI

modules/gob-web/routes/create/method-upload.js
I haven't dispatched route changes in … a very long time.
Fixes #2225
=> Stop crashing after importing a student

modules/gob-web/routes/create/method-import.js
the actual problem here was that I was importing a gb student through the sis import mechanism
=> add more logging when importing a student

modules/gob-web/routes/degub/index.js, modules/gob-web/routes/edit-area/index.js, modules/gob-web/routes/index.js, modules/gob-web/routes/search/index.js
=> remove remaining require.ensure calls

modules/gob-web/modules/course-table/__tests__/__snapshots__/year.test.js.snap, modules/gob-web/modules/course-table/year.js
=> Remove small caps from year control buttons text

modules/gob-web/modules/student-picker/student-list-item.js
=> Use large trash icon on student list item in student picker

modules/gob-web/modules/course/modal.js
=> Hide disabled schedule button on modal view

.flowconfig, modules/gob-hanson-format/__tests__/parse-hanson-string/parse-hanson-string.support.js, modules/gob-object-student/find-course-warnings.js, modules/gob-web-database/__mocks__/index.js, modules/gob-worker-load-data/source/__tests__/clean-prior-data.test.js, modules/gob-worker-load-data/source/__tests__/get-cache-store-name.test.js, modules/gob-worker-load-data/source/__tests__/parse-data.test.js, modules/gob-worker-load-data/source/__tests__/remove-duplicate-areas.test.js
=> Flow tweaks

modules/gob-area-editor/app.js, modules/gob-area-editor/components/loading.js, modules/gob-area-editor/components/monaco.js, modules/gob-area-editor/index.js, modules/gob-area-editor/package.json, modules/gob-area-editor/screens/m-editor.js, modules/gob-area-editor/start.js, modules/gob-area-editor/webpack.config.js, modules/gob-web/package.json, modules/gob-web/routes/edit-area/index.js, modules/gob-web/webpack.config.js, yarn.lock
=> Add an interactive "area editor"

modules/gob-web/modules/area-of-study/expression.js, modules/gob-web/modules/area-of-study/expression.scss
See the checkmark on the AQR entry
before | after
--- | ---
=> Clean up <Expression/> a bit

modules/gob-web/modules/course/expanded.js
=> List each course description element as a paragraph

modules/gob-web/modules/course/offerings.js
If they've been grouped, then we know there's at least one.
=> Remove possibility of null offerings

modules/gob-web/modules/course-searcher/lib.js
=> sort years after extraction

modules/gob-web/package.json, modules/gob-worker-load-data/package.json, yarn.lock
- copy-webpack-plugin
- react-dropzone
- serialize-error
- delay
- mini-css-extract-plugin
- url-loader
- styled-components
=> Dep updates

modules/gob-web/modules/course/expanded.js, modules/gob-web/modules/course/modal.js, modules/gob-web/modules/course/warnings.js
Shows the warnings on the course modal.
=> Show course warnings on modal

modules/gob-web/modules/student/student-summary.js
* Adds 10 new greetings
* Updates origin comments
=> Update greetings and origin comments

modules/gob-web/screens/degub.js
The student prop has changed quite a bit. Updates degub to read the right props from student to prevent crashing and erring.
=> Update degub props

.circleci/config.yml, modules/gob-web/package.json, modules/gob-web/webpack.config.js, yarn.lock
https://packtracker.io/
webpack stats? something something
=> Add Packtracker

modules/gob-web/redux/students/actions/__tests__/destroy.test.js
it's not part of the spec for localStorage
=> Remove use of hasItem
