hawkrives/gobbldygook

app/models/student.js

OrderedMaps maintain their insertion order, thus when we translate from
the raw JSON into a Student and back, we maintain the sort order
instead of losing it.
That's my reason.

Use OrderedMaps instead of Maps in Student

---

app/models/study.js
test/models/study.test.js

Originally, this was going to facilitate the rearrangement of areas-of-study in the sidebar. 
We don't currently support rearrangement of areas-of-study in the sidebar. I don't think that we want to. 
We also currently ignore the `index` property when rendering areas into the sidebar.
I'm just going for a complete gutting of this feature-that-never-was.

Remove 'index' support from Study

---

app/helpers/queryTreoDatabase.js
package.json

Treo used to (I swear!) expect you to get the `treo` object from the constructor of the `db` param. Now, it passes it in as the second parameter.
Moreover, `treo.range` has been extracted to the `idb-range` package on npm. This updates `queryTreoDatabase` to use that package.

Fix treo after update to 0.4.1

---

app/elements/areaOfStudy.js
app/elements/graduationStatus.js
app/helpers/checkStudentGraduatability.js
app/models/student.js
app/styles/app/areaOfStudy.styl
app/styles/app/requirementSet.styl
package.json

GraduationStatus's rendering shouldn't be blocked by checkStudentAgainstArea, IMO.
Therefore, I've rebuilt chunks of AreaOfStudy and GraduationStatus in order to load the results asychronously.
GradStatus still runs the result finder, but now also renders areas before recieving the results. (This is made possible by loading the area in the Study constructor.)
This might not be enough, still; if we transitions Study to retrieve props in an async fashion, this expects to have everything but the results immediately. Well, let's cross that :bridge: when we come to it.
:shipit:, @drewvolz?

Make area of study loading, in the sidebar, async

---

app/elements/areaOfStudy.js
app/elements/booleanArrayRequirement.js
app/elements/booleanRequirement.js
app/elements/course.js
app/elements/courseTable.js
app/elements/expandedCourse.js
app/elements/numberObjectRequirement.js
app/elements/searchButton.js
app/elements/semester.js
app/elements/someArrayRequirement.js
package.json

Also converges on using `{...{}}` (ES7 object destructuring), instead of `Object.assign` or `_.extend`.

Use classnames instead of React.addons.classSet

---

benchmarks/students-benchmark.js
src/base/variables.scss
src/components/expression--course.js
src/components/expression--course.scss
src/components/expression.scss
src/components/requirement.js
src/components/requirement.scss
src/lib/compute-chunk.js
test/areas/compute-boolean.test.js
test/areas/compute-course.test.js
test/areas/compute-modifier.test.js
test/example-students/computer-science-load-1.json

Before, it would render all of the information from the matched course; now, it only renders the information in the requirement.
---
We have to merge the course query and found course objects when we encounter them, but that led to rendering all of the information from the merged course in the block.
Which felt to me like it implied that you had to have taken this specific course, when all it meant was that this course happened to match.

Only render the required chunks for courses in <AreaOfStudy/>

---

CHANGELOG.md
src/components/course-title.js
src/components/course.scss

When showing courses whose `name` and `title` are often different, such as for Seminar and Topics courses, we should show both the name and the title.

Show subtitles on courses

---

.eslintrc
.webpackrc
package.json
src/models/student.js

I started down this path because I noticed (using source-map-explorer[1]) that Esprima was being bundled into the browser bundle.
So I used the `webpack.IgnorePlugin` to ignore it.
Then I got annoyed by the constant logging of messages during tests, so I decided that I should use a logging module (like `debug`) to provide control over when messages are logged; so I used the `webpack.ProvidePlugin` to make it a global.
I also remembered that the entire `package.json` was being required, so I look at it, saw that it only needed the `version` key, and used `ProvidePlugin` to expose that as a `VERSION` global.
Fun times!
[1]: `source-map-explorer build/gobbldygook.3.0.0-beta3.js build/gobbldygook.3.0.0-beta3.js.map`

use shiny Webpack features

---

area-data/majors/mathematics.yaml
src/area-tools/compute.js
src/area-tools/enhance-hanson.js

Primarily for the math major: if a requirement is set to `children share courses = true`, then they share courses. The default is false (well, undefined).
If they don't share courses, then they share the dirty set; if they do, however, they each receive their own dirty set, so that they don't know if a course has been used yet or not.
`children share courses` is non-recursive.

Add the ability to have requirements not share a dirty list

---

src/components/inline-course.js
src/components/inline-course.scss
src/routes/student_content_course-table/components/course-list.scss
src/routes/student_content_course-table/components/semester.js

Fixes #820.
They were missing for two reasons: one, the courses weren't re-rendering when the conflicts changed, and two, a thing changed a while ago in the structure of the validation objects so no conflicts were actually being passed _to_ the courses in the first place.

Show scheduling issues again

---

package.json
yarn.lock

Update babel-runtime, babel-core, babel-loader, and babel-plugin-transform-object-rest-spread.
closes #1095
closes #1081
closes #1079

upgrade babel-* dependencies

---

modules/web/redux/middleware/save-students.js

allows you to undo an action and have the undoed state be present when you come back

add UNDO/REDO to the whitelist of actions to save after

---

package.json
yarn.lock

`nyc` was replaced with `jest`'s coverage mode.
`mock-require` is not used in the codebase anywhere.

Remove some unused deps

---

modules/hanson-format/enhance-hanson.js

It's not implemented, but this way it won't fail to parse.

add "contract" to the enhanceHanson whitelist

---

modules/web/helpers/check-student-against-area.worker.js
modules/web/helpers/load-data.worker.js

`debug`, I think, needs to check for a property in localStorage to enable itself, but localStorage isn't present in web workers, so it's never enabled.
This switches to console.log, instead.

Fix logging in web workers

---

modules/web/components/content-editable.js
modules/web/modules/student/student-summary.js

This PR reworks the hideous mess that is &lt;StudentSummary/> into a somewhat more manageable mess, by the power of ~~Grayskull~~ React components.
I split it into a bunch of littler components, with most of that string manipulation stuff relegated to a new `<DegreeSummary/>` component.
Compare: [old][old] to [new][new].
[old]: https://github.com/hawkrives/gobbldygook/blob/b9693058c73839feeae07f385dc7eb6668d87498/modules/web/modules/student/student-summary.js
[new]: https://github.com/hawkrives/gobbldygook/blob/33dab7c7ab5564f6fa69d7c2bc1562a6be7aea7f/modules/web/modules/student/student-summary.js

StudentSummary rework

---

modules/examine-student/pluralize-area.js
modules/web/helpers/get-courses.js
modules/web/helpers/load-area.js
modules/web/index.js

> The proper solution to this would be to fix whatever is telling Safari "you don't need to update any files" in loadData.
This PR:
- adds a dynamic switch based on browser to allow the app to load data from the network instead of the database
- allows pluralizeArea to take any string, instead of just the enumerated ones
This PR allows Safari/Mobile Safari to evaluate _existing_ student files. You will need to export an existing file, then import it into the Safari copy of the app.

Add a Safari-based toggle for disabling database access

---

package.json

fix(package): update sto-sis-time-parser to version 2.2.13

---

modules/gob-web/components/avatar-letter.js

I don't think it's needed, and it's causing #2226
Closes #2226

Remove margin:0 from AvatarLetter

---

modules/gob-web/routes/create/method-upload.js

- renames state.students to state.actions, to better describe what it contains (student creation actions, that is)
- properly uses setState callbacks to ensure that data is updated in the proper sequence
- replaces a long promise chain with an async function

clean up some processes in UploadStudentFile

---

modules/gob-web/modules/student-picker/student-list.js

Currently the student items show the newest at the bottom when sorting by modified. This reverses that to show them at the top of the list. It feels more natural.

Show newest modified student items at the top

---

modules/gob-object-student/types.js

Term is used in the fabrication listings, but it's not listed in the type.

Add term to fabrication type

---

modules/gob-web/helpers/save-student.js
modules/gob-web/redux/index-development.js
modules/gob-web/redux/index-production.js
modules/gob-web/redux/middleware/save-student.js
modules/gob-web/redux/students/actions/change.js
modules/gob-web/redux/students/constants.js

Restores the save-students middleware and removes the requirement for having change-student save during the execution of the action.
Closes #2285

Save students on undo/redo

---

modules/gob-search-queries/build-query-from-string.js

If you just type "SPM" into the search box, it will now automatically convert to `gereqs:SPM` and thus only return courses with SPM requirements.
The list of gereqs is hard-coded, currently, and FOL is broken out into FOL-J/A/K, etc.

Automatically search for gereqs

---

modules/gob-web/modules/course/expanded.js
modules/gob-web/modules/course/offerings.js

* Condenses offerings into condensed repeated schedules
* Separates day names with slashes
* Adds non-breaking spaces between location strings to keep them on the same line

Condense course offerings in modal

---

modules/gob-web/modules/area-of-study/area-of-study.js
modules/gob-web/modules/area-of-study/area-of-study.scss
modules/gob-web/modules/area-of-study/expression.js
modules/gob-web/modules/area-of-study/expression.scss
modules/gob-web/modules/area-of-study/requirement.js
modules/gob-web/modules/area-of-study/requirement.scss

Before | After
--- | ---
Overall, I like the new look - they are bigger hit targets; the bolder borders make it easier to visually parse the requirements; and hiding the duplicate listing of requirement references really helps.
Also, areas now start collapsed, to help avoid information overload. You can still expand them, but now it's more exploratory.

Area tweaks

---

modules/gob-web/modules/course-searcher/lib.js
modules/gob-web/modules/course-searcher/querent.js
modules/gob-web/modules/course-searcher/results-list.js
modules/gob-web/modules/course-searcher/searcher.js
modules/gob-web/modules/course-searcher/searcher.scss

"filter by" lets you filter down to just a specific group in the list, so if you group by term, you can only see that term; if you group by department, you can only see that department; etc. It's live with respect to your current "group by" option.
"limit to {year}" lets you easily limit the results to a specific year. It's applied first, so if you limit to 2012, you'll only see grouping options for 2012, etc.
---
Known issues:

Implement "filter by" and "limit to" search fields in the sidebar

---

modules/gob-web/modules/course/expanded.js

Fixing something I introduced in #2300

Remove nested paragraphs from course description

---

modules/gob-web/modules/area-of-study/area-of-study.js
modules/gob-web/modules/area-of-study/connected.js
modules/gob-web/modules/student/area-of-study-group.js

With the new area picker interface, which has giant [X] buttons attached to each entry, I don't think that we need the (x) buttons on the individual areas any longer.
Plus, they're buggy wrt. layout currently, ever since we added extra padding to FlatButton&co.
Closes #2306

Remove the remove-area buttons from the "edit area group" mode

---

modules/gob-web/screens/student/index.js

The prop became lost from a refactor, so this brings back the greetings! 
To follow -- more greetings.

Bring back randomized greetings on the planner

---

modules/gob-web/modules/course/modal.js

More space at the bottom of the bottomtoolbar

---

modules/gob-web/app.js
modules/gob-web/modules/student/student.js

* Page for when student could not be loaded (student)
* Page for when the resource could not be loaded (404)
Before | After
--|--

Show certain pages as cards

---

modules/gob-web/package.json
yarn.lock

v1.1.1 contains a fix so that our data should actually start populating the database.

update packtracker to v1.1.1

---

modules/gob-web/helpers/db.js
modules/gob-web/index.js

because I was trying to use it earlier, and it's not loaded on the main screen anymore.

Always attach the window._db global instead of waiting for helpers/db to be loaded
